name: playlette
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - matplotlib
  - matplotlib-inline
  - seaborn
  - numpy
  - polars
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - spotipy
  - flask
  - tqdm
  - requests
  - requests-oauthlib
  - pydantic
  - PyYAML
  - pyarrow
  - pip